Adds lib function and steps for rapidast nightly pipeline
RedHatInsights/insights-pipeline-lib pull request #199
Opened 2023-07-14 10:47 UTC by san7ket

- Adds a parse_rapidast_options to create a valid config file from essentials parameter needed by rapidast scanner
-  Adds pipeline steps to create a jenkins jobs for rapidast

2023-07-18 12:50 UTC, ntkathole commented on vars/rapidastUtils.groovy
> + openShiftUtils.withNode(cloud: 'upshift', image: 'quay.io/sjagtap/rapidast-test:latest') {
Use pipelineVars.upshiftCloud var instead of upshift hardcoded

2023-07-18 12:51 UTC, ntkathole commented on vars/rapidastUtils.groovy
> + openShiftUtils.withNode(cloud: 'upshift', image: 'quay.io/sjagtap/rapidast-test:latest') {
Should image quay.io/sjagtap/rapidast-test be under in insights/cloudservices quay org?

2023-07-18 12:55 UTC, ntkathole commented on vars/rapidastUtils.groovy
> +    sh "git clone https://github.com/RedHatProductSecurity/rapidast.git"
[Optional] You can use gitUtils.checkOutRepo here

2023-07-18 12:56 UTC, ntkathole commented on vars/rapidastUtils.groovy
> +        final String sso_url = "https://sso.stage.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
[Optional] There is central place to store all vars at https://github.com/RedHatInsights/insights-pipeline-lib/blob/master/vars/pipelineVars.groovy , which can be used to maintain these values

2023-07-18 12:58 UTC, ntkathole commented on vars/rapidastUtils.groovy
> +        sh "sed -i 's/importUrlsFromFile:/# importUrlsFromFile:/' config/config-template-long.yaml"
How about replacing filename var defined above with "config/config-template-long.yaml" in all sed commands ?

2023-07-19 14:35 UTC, ntkathole submitted a review, later dismissed
LGTM 👍

2023-07-20 14:57 UTC, bsquizz requested changes

2023-07-20 14:57 UTC, bsquizz commented on vars/pipelineVars.groovy
> +    String stageSS0Url = "https://sso.stage.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
Can you use a the letter "O" instead of number "0" here? :) It is currently `stageSS0Url`

2023-07-20 14:57 UTC, bsquizz commented on vars/rapidastUtils.groovy
> + openShiftUtils.withNode(cloud: pipelineVars.upshiftCloud, image: 'quay.io/insights-qe/rapidast:multiuser') {
Can the indents/spacing in here be cleaned up.

2023-07-20 14:57 UTC, bsquizz commented on vars/rapidastUtils.groovy
> +def prepareRapidastStages(String ServiceName, String ApiScanner, String TargetUrl ,String ApISpecUrl) {
Can you remove the extra whitespace after 'TargetUrl'

2023-07-20 19:38 UTC, bsquizz approved these changes

2023-07-20 19:38 UTC, merged